-- location-service schema. Matches com.assettracker.locationservice.entity.Location.
CREATE TABLE locations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT NOT NULL,
    kind       VARCHAR(20)  NOT NULL,
    label      VARCHAR(255) NOT NULL,
    building   VARCHAR(255),
    floor      VARCHAR(255),
    qr_tag     VARCHAR(64)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_locations_client ON locations (client_id);
CREATE UNIQUE INDEX ux_locations_qr_tag ON locations (qr_tag);
