-- assignment-service schema. Matches com.assettracker.assignmentservice.entity.Assignment.
CREATE TABLE assignments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      BIGINT NOT NULL,
    asset_id       BIGINT NOT NULL,
    holder_type    VARCHAR(20)  NOT NULL,
    holder_id      BIGINT NOT NULL,
    checked_out_by VARCHAR(255) NOT NULL,
    checked_out_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    returned_at    TIMESTAMP(6) WITH TIME ZONE,
    returned_by    VARCHAR(255),
    note           VARCHAR(2000)
);
CREATE INDEX ix_assignments_client ON assignments (client_id);
CREATE INDEX ix_assignments_asset ON assignments (asset_id);
CREATE INDEX ix_assignments_holder ON assignments (holder_type, holder_id);
-- at most one open assignment per asset
CREATE UNIQUE INDEX ux_assignments_open_asset ON assignments (asset_id) WHERE returned_at IS NULL;
