-- Append-only audit trail for asset changes.
CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL,
    actor       VARCHAR(255) NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    entity_type VARCHAR(32)  NOT NULL,
    entity_id   BIGINT NOT NULL,
    summary     VARCHAR(500) NOT NULL,
    detail      TEXT,
    at          TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_client ON audit_events (client_id, at DESC);
CREATE INDEX ix_audit_entity ON audit_events (entity_type, entity_id, at DESC);
CREATE INDEX ix_audit_actor ON audit_events (actor);
