-- Event sign-out: an employee asks for gear for a named event, an approver rules on it,
-- a tech hands it out. Fulfilment still goes through the normal check-out path, so the
-- assignments table remains the single record of who holds what.
CREATE TABLE event_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id           BIGINT       NOT NULL,
    event_name          VARCHAR(160) NOT NULL,
    event_date          DATE         NOT NULL,
    location            VARCHAR(160),
    notes               VARCHAR(1000),
    requested_by        VARCHAR(255) NOT NULL,
    requester_person_id BIGINT,
    status              VARCHAR(20)  NOT NULL,
    decided_by          VARCHAR(255),
    decided_at          TIMESTAMP(6) WITH TIME ZONE,
    decision_note       VARCHAR(500),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_event_requests_client_date ON event_requests (client_id, event_date DESC);
CREATE INDEX ix_event_requests_requester ON event_requests (client_id, requester_person_id);

CREATE TABLE event_request_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          BIGINT      NOT NULL REFERENCES event_requests (id),
    item_type           VARCHAR(80) NOT NULL,
    quantity            INTEGER     NOT NULL,
    notes               VARCHAR(500),
    fulfilled_asset_ids VARCHAR(500)
);

CREATE INDEX ix_event_request_lines_request ON event_request_lines (request_id);
