-- What a client owns for events, and how many. Separate from the asset catalog on purpose:
-- the catalog tracks individual units by serial, while an event request is raised against a
-- pool ("2 TVs"), before anyone knows which two. The pool is what the sign-out form offers and
-- what availability is measured against; fulfilment still names real assets and checks them out.
CREATE TABLE event_equipment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT      NOT NULL,
    item_type  VARCHAR(80) NOT NULL,
    quantity   INTEGER     NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- One row per item type per client: "Acme has 2 TVs" is a fact with one answer.
CREATE UNIQUE INDEX ux_event_equipment_client_item ON event_equipment (client_id, item_type);
