-- Check-out is not a single transaction: it calls asset-service over HTTP, then writes
-- history, then publishes an event. A client that retries after a timeout - or a user who
-- double-clicks - can therefore send the same intent twice, and the second attempt is
-- rejected with 409 "already assigned" even though the caller's operation succeeded. The
-- caller cannot tell that apart from a real conflict.
--
-- An idempotency key makes the retry safe: the same key replays the original answer instead
-- of doing the work again.
CREATE TABLE idempotency_keys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT       NOT NULL,
    idem_key      VARCHAR(120) NOT NULL,
    -- what was asked for, so a key reused with a different body is caught rather than
    -- silently replaying an answer to a question nobody asked
    request_hash  VARCHAR(64)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    assignment_id BIGINT,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at  TIMESTAMP(6) WITH TIME ZONE
);

-- The whole mechanism rests on this: two concurrent retries race to insert, exactly one
-- wins, and the loser is told the work is already in flight rather than repeating it.
CREATE UNIQUE INDEX ux_idempotency_keys_client_key ON idempotency_keys (client_id, idem_key);
