-- people-service schema. Matches com.assettracker.peopleservice.entity.Person.
CREATE TABLE people (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    department VARCHAR(255),
    desk_id    BIGINT,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_people_client ON people (client_id);
CREATE UNIQUE INDEX ux_people_client_email ON people (client_id, LOWER(email));
