-- client-service schema. Matches com.assettracker.clientservice.entity.Client.
CREATE TABLE clients (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    slug       VARCHAR(40)  NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_clients_slug ON clients (slug);
