-- asset-service schema. Matches com.assettracker.assetservice.entity.Asset.
CREATE TABLE assets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id           BIGINT NOT NULL,
    type                VARCHAR(20)  NOT NULL,
    make                VARCHAR(255),
    model               VARCHAR(255),
    serial_number       VARCHAR(255) NOT NULL,
    asset_tag           VARCHAR(64)  NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    holder_type         VARCHAR(20)  NOT NULL,
    holder_id           BIGINT,
    purchase_date       DATE,
    purchase_cost_cents BIGINT,
    notes               VARCHAR(2000),
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_assets_client ON assets (client_id);
CREATE INDEX ix_assets_holder ON assets (holder_type, holder_id);
CREATE UNIQUE INDEX ux_assets_tag ON assets (asset_tag);
