-- Types are now per-client rows a tech can add and remove, not a fixed enum.
-- assets.type keeps the type *name* (not a foreign key) so removing a type never
-- cascades to assets; the service blocks the delete while any asset still uses it.
ALTER TABLE assets ALTER COLUMN type TYPE VARCHAR(64);

CREATE TABLE asset_types (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT      NOT NULL,
    name       VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_asset_types_client_name ON asset_types (client_id, lower(name));
CREATE INDEX ix_assets_client_type ON assets (client_id, type);
