-- Spreadsheet import. `attributes` keeps the client's own columns that we don't
-- model (stored as a JSON string in TEXT for H2/Postgres portability).
ALTER TABLE assets ADD COLUMN attributes TEXT;

-- A saved column -> field mapping so a client's monthly re-upload is one click.
CREATE TABLE import_profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT       NOT NULL,
    name        VARCHAR(120) NOT NULL,
    mapping     TEXT         NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_import_profiles_client_name ON import_profiles (client_id, lower(name));
