-- auth-service schema. Matches com.assettracker.authservice.entity.User.
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

-- the tenant ids a user may act on (mirrored into the JWT 'clientIds' claim)
CREATE TABLE user_client_ids (
    user_id   BIGINT NOT NULL REFERENCES users (id),
    client_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, client_id)
);
